# 配置文件

server:
  port: 8080

# 路由配置
routes:
  # 路由service-a
  - id: service-a
    path: /service-a
    targets: 
          - http://localhost:8081
          - http://localhost:8082
  # 路由service-b
  - id: service-b
    path: /service-b
    targets: 
          - http://localhost:8083
          - http://localhost:8084
